name: NC RESPO ENGINE

on:
  push:
    paths:
      - "NC/**"
      - ".github/workflows/static.yml"
  workflow_dispatch:

jobs:
  respo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ROOT-SIGNAL LADEN
        run: cat .github/workflows/static.yml

      - name: SCAN
        run: ls -R NC

      - name: AUTOSAVE
        run: cp NC/RW/state.json NC/BK/backup.json

      - name: AUTOLOAD
        run: cp NC/SL/edit.json NC/RW/state.json
